language: generic
os: osx
sudo: false


matrix:
  include:
    - osx_image: xcode9.4
      env:
      - PYTHON_VERSION=2.7.15
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - osx_image: xcode9.3
      env:
      - PYTHON_VERSION=2.7.15
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - osx_image: xcode9.2
      env:
      - PYTHON_VERSION=2.7.15
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - osx_image: xcode9.1
      env:
      - PYTHON_VERSION=2.7.15
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - osx_image: xcode9
      env:
      - PYTHON_VERSION=2.7.15
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - osx_image: xcode8.3
      env:
      - PYTHON_VERSION=2.7.15
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - osx_image: xcode8
      env:
      - PYTHON_VERSION=2.7.15
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - osx_image: xcode7.3
      env:
      - PYTHON_VERSION=2.7.15
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - osx_image: xcode6.4
      env:
      - PYTHON_VERSION=2.7.15
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

before_install:
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      brew update > /dev/null;
      brew outdated pyenv || brew upgrade --quiet pyenv;

      PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs2" pyenv install -ks $PYTHON_VERSION;
      pyenv global $PYTHON_VERSION;
    fi

install:
  - which python pip
  - python --version
  - pip install -U pip
  - pip --version
  - pip install chainer

script:
  - wget "https://raw.githubusercontent.com/chainer/chainer/v4.2.0/examples/mnist/train_mnist.py"
  - python train_mnist.py --epoch 3
